### ISSUE TITLE
Wireguard PostDown

### ISSUE THREAD

**Issue by dickiesanders** [elghazal-a/autowire#1]
Autowire doesn't have an option to submit "PostDown" commands.

[Server Config](https://wiki.archlinux.org/index.php/WireGuard#Key_generation)

```
[Interface]
Address = 10.200.200.1/24
ListenPort = 51820
PrivateKey = SERVER_PRIVATE_KEY

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by elghazal-a** [comment]
Yes you're right, it supports only `--post-up`. But it's straightforward to add support for `PostDown`. PRs are welcome

**Comment by dickiesanders** [comment]
@geniousphp - I started to make a PR but I'm fairly new to Golang, so I wasn't sure how to build the project without the missing "vendor" folder.

**Comment by elghazal-a** [comment]
@dickiesanders The dependencies are managed by https://github.com/golang/dep, it's seem it's deprecated now so I might want to replace it.

**Comment by elghazal-a** [comment]
v0.2.0 supports `PostDown` now
