### ISSUE TITLE
Rebind Consul to wireguard interface

### ISSUE THREAD

**Issue by Brandl** [elghazal-a/autowire#4]
First off congratulations on execution of a genius idea.
I was looking for a solution to exactly that problem.

One minor feature that I would like to see added would be to no also autoconfigure wireguard via consul but also move all consul instances over to the new wireguard network.

Is this even possible or would this create a chicken-egg problem where one relies on the other?

**Comment by elghazal-a** [comment]
Thank you @Brandl 

I understand your need and I confirm that this can create a CE problem. Besides, I'm designing AutoWire to manage wireguard and not Consul. Consul is only used as backend storage. 

You can always have your config management system reconfigure consul interfaces

I'm closing the issue. Feel free to re-open it if you need to
